// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Netficks.Data;

#nullable disable

namespace Proiect_Netficks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250515200107_IWillKiillMyself")]
    partial class IWillKiillMyself
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Abonament", b =>
                {
                    b.Property<int>("Abonament_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Abonament_ID"));

                    b.Property<DateTime>("Data_Sfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Utilizator_ID")
                        .HasColumnType("int");

                    b.HasKey("Abonament_ID");

                    b.HasIndex("UserId");

                    b.HasIndex("Utilizator_ID");

                    b.ToTable("Abonamente");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Episod", b =>
                {
                    b.Property<int>("Episod_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Episod_ID"));

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<int>("Numar_Episod")
                        .HasColumnType("int");

                    b.Property<int>("Numar_Sezon")
                        .HasColumnType("int");

                    b.Property<int>("Serial_ID")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Episod_ID");

                    b.HasIndex("Serial_ID");

                    b.ToTable("Episoade");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Film", b =>
                {
                    b.Property<int>("Film_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Film_ID"));

                    b.Property<int>("An_Lansare")
                        .HasColumnType("int");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durata")
                        .HasColumnType("int");

                    b.Property<int>("Gen_ID")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Film_ID");

                    b.HasIndex("Gen_ID");

                    b.ToTable("Filme");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Gen", b =>
                {
                    b.Property<int>("Gen_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gen_ID"));

                    b.Property<string>("Nume_Gen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Gen_ID");

                    b.ToTable("Genuri");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Istoric_Vizionari", b =>
                {
                    b.Property<int>("Vizionare_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Vizionare_ID"));

                    b.Property<DateTime>("Data_Vizionare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Episod_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Film_ID")
                        .HasColumnType("int");

                    b.Property<int>("Timp_Vizionare")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Utilizator_ID")
                        .HasColumnType("int");

                    b.HasKey("Vizionare_ID");

                    b.HasIndex("Episod_ID");

                    b.HasIndex("Film_ID");

                    b.HasIndex("UserId");

                    b.HasIndex("Utilizator_ID");

                    b.ToTable("IstoricVizionari");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Lista_Mea", b =>
                {
                    b.Property<int>("Lista_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lista_ID"));

                    b.Property<DateTime>("Data_Creare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Film_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Serial_ID")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Utilizator_ID")
                        .HasColumnType("int");

                    b.HasKey("Lista_ID");

                    b.HasIndex("Film_ID");

                    b.HasIndex("Serial_ID");

                    b.HasIndex("UserId");

                    b.HasIndex("Utilizator_ID");

                    b.ToTable("ListaMea");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Recenzii", b =>
                {
                    b.Property<int>("Recenzie_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Recenzie_ID"));

                    b.Property<string>("Comentariu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("Data_Postarii")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Episod_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Film_ID")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Utilizator_ID")
                        .HasColumnType("int");

                    b.HasKey("Recenzie_ID");

                    b.HasIndex("Episod_ID");

                    b.HasIndex("Film_ID");

                    b.HasIndex("UserId");

                    b.HasIndex("Utilizator_ID");

                    b.ToTable("Recenzii");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Serial", b =>
                {
                    b.Property<int>("Serial_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Serial_ID"));

                    b.Property<int>("An_Aparitie")
                        .HasColumnType("int");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gen_ID")
                        .HasColumnType("int");

                    b.Property<int>("Numar_Sezoane")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Serial_ID");

                    b.HasIndex("Gen_ID");

                    b.ToTable("Seriale");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_Inregistrare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip_Abonament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Utilizator", b =>
                {
                    b.Property<int>("Utilizator_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Utilizator_ID"));

                    b.Property<DateTime>("Data_Inregistrare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tip_Abonament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Utilizator_ID");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Abonament", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany("Abonamente")
                        .HasForeignKey("UserId");

                    b.HasOne("Proiect_Netficks.Models.Utilizator", "Utilizator")
                        .WithMany("Abonamente")
                        .HasForeignKey("Utilizator_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Episod", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Serial", "Serial")
                        .WithMany("Episoade")
                        .HasForeignKey("Serial_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Serial");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Film", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Gen", "Gen")
                        .WithMany("Filme")
                        .HasForeignKey("Gen_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gen");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Istoric_Vizionari", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Episod", "Episod")
                        .WithMany("IstoricVizionari")
                        .HasForeignKey("Episod_ID");

                    b.HasOne("Proiect_Netficks.Models.Film", "Film")
                        .WithMany("IstoricVizionari")
                        .HasForeignKey("Film_ID");

                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany("IstoricVizionari")
                        .HasForeignKey("UserId");

                    b.HasOne("Proiect_Netficks.Models.Utilizator", "Utilizator")
                        .WithMany("IstoricVizionari")
                        .HasForeignKey("Utilizator_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episod");

                    b.Navigation("Film");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Lista_Mea", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Film", "Film")
                        .WithMany("ListaMea")
                        .HasForeignKey("Film_ID");

                    b.HasOne("Proiect_Netficks.Models.Serial", "Serial")
                        .WithMany("ListaMea")
                        .HasForeignKey("Serial_ID");

                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany("ListaMea")
                        .HasForeignKey("UserId");

                    b.HasOne("Proiect_Netficks.Models.Utilizator", "Utilizator")
                        .WithMany("ListaMea")
                        .HasForeignKey("Utilizator_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Serial");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Recenzii", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Episod", "Episod")
                        .WithMany("Recenzii")
                        .HasForeignKey("Episod_ID");

                    b.HasOne("Proiect_Netficks.Models.Film", "Film")
                        .WithMany("Recenzii")
                        .HasForeignKey("Film_ID");

                    b.HasOne("Proiect_Netficks.Models.User", null)
                        .WithMany("Recenzii")
                        .HasForeignKey("UserId");

                    b.HasOne("Proiect_Netficks.Models.Utilizator", "Utilizator")
                        .WithMany("Recenzii")
                        .HasForeignKey("Utilizator_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episod");

                    b.Navigation("Film");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Serial", b =>
                {
                    b.HasOne("Proiect_Netficks.Models.Gen", "Gen")
                        .WithMany("Seriale")
                        .HasForeignKey("Gen_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gen");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Episod", b =>
                {
                    b.Navigation("IstoricVizionari");

                    b.Navigation("Recenzii");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Film", b =>
                {
                    b.Navigation("IstoricVizionari");

                    b.Navigation("ListaMea");

                    b.Navigation("Recenzii");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Gen", b =>
                {
                    b.Navigation("Filme");

                    b.Navigation("Seriale");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Serial", b =>
                {
                    b.Navigation("Episoade");

                    b.Navigation("ListaMea");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.User", b =>
                {
                    b.Navigation("Abonamente");

                    b.Navigation("IstoricVizionari");

                    b.Navigation("ListaMea");

                    b.Navigation("Recenzii");
                });

            modelBuilder.Entity("Proiect_Netficks.Models.Utilizator", b =>
                {
                    b.Navigation("Abonamente");

                    b.Navigation("IstoricVizionari");

                    b.Navigation("ListaMea");

                    b.Navigation("Recenzii");
                });
#pragma warning restore 612, 618
        }
    }
}
